#!/bin/bash

Cat is wild animal.
cats are friendly.
cat is wild animal.
cat is wild animal.
White is good color.
White is good color.
Black is opposite to blue color.
Dogs and cats are best friends.
cAt is a pet.
CaT is a pet.
